/**
 * @file kws_engine.c
 * @brief TensorFlow Lite Micro inference for DS-CNN-S.
 *
 * Loads the INT8-quantised model from flash, allocates an arena in PSRAM
 * (or internal SRAM), and runs inference on (49, 10) MFCC features.
 *
 * Inference time target: < 20 ms on ESP32-C5 @ 240 MHz.
 */

#include "kws_engine.h"
#include "spectra_config.h"
#include "spectra_model.h"  /* auto-generated by export_tflite.py */

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "esp_log.h"
#include "esp_timer.h"
#include <math.h>
#include <string.h>

static const char *TAG = "kws_engine";

/* ── TFLite Micro arena ─────────────────────────────────────────── */

/*
 * Tensor arena: working memory for TFLite Micro.
 * 40 KB should be sufficient for DS-CNN-S (~22 k params).
 * Allocate in .bss or PSRAM if available.
 */
#define TENSOR_ARENA_SIZE (40 * 1024)
static uint8_t s_tensor_arena[TENSOR_ARENA_SIZE] __attribute__((aligned(16)));

/* ── TFLite objects (static lifetime) ───────────────────────────── */

static const tflite::Model *s_model = nullptr;
static tflite::MicroInterpreter *s_interpreter = nullptr;
static TfLiteTensor *s_input_tensor = nullptr;
static TfLiteTensor *s_output_tensor = nullptr;

static int64_t s_last_inference_us = 0;

/* ── Op Resolver ────────────────────────────────────────────────── */

/*
 * Register only the ops used by DS-CNN-S:
 *   - Conv2D
 *   - DepthwiseConv2D
 *   - FullyConnected (Dense)
 *   - MaxPool2D (if used)
 *   - Mean (for global average pooling)
 *   - Reshape
 *   - Softmax
 *   - Quantize / Dequantize
 */
typedef tflite::MicroMutableOpResolver<8> OpResolver;

static void register_ops(OpResolver &resolver)
{
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddFullyConnected();
    resolver.AddMaxPool2D();
    resolver.AddMean();              /* for GlobalAveragePooling2D */
    resolver.AddReshape();
    resolver.AddSoftmax();
    resolver.AddQuantize();
    resolver.AddDequantize();
}

/* ── Public API ─────────────────────────────────────────────────── */

int kws_engine_init(void)
{
    ESP_LOGI(TAG, "Initialising KWS engine...");
    ESP_LOGI(TAG, "  Model size: %u bytes (%.1f KB)", spectra_model_len, spectra_model_len / 1024.0f);
    ESP_LOGI(TAG, "  Tensor arena: %d bytes (%.1f KB)", TENSOR_ARENA_SIZE, TENSOR_ARENA_SIZE / 1024.0f);

    /* Verify model magic number */
    s_model = tflite::GetModel(spectra_model);
    if (s_model->version() != TFLITE_SCHEMA_VERSION) {
        ESP_LOGE(TAG, "Model schema version mismatch: expected %d, got %d",
                 TFLITE_SCHEMA_VERSION, s_model->version());
        return -1;
    }

    /* Register ops */
    static OpResolver resolver;
    register_ops(resolver);

    /* Create interpreter */
    static tflite::MicroInterpreter interpreter(
        s_model, resolver, s_tensor_arena, TENSOR_ARENA_SIZE
    );
    s_interpreter = &interpreter;

    /* Allocate tensors */
    TfLiteStatus status = s_interpreter->AllocateTensors();
    if (status != kTfLiteOk) {
        ESP_LOGE(TAG, "AllocateTensors failed!");
        return -1;
    }

    /* Get input/output tensors */
    s_input_tensor = s_interpreter->input(0);
    s_output_tensor = s_interpreter->output(0);

    ESP_LOGI(TAG, "  Input:  type=%d, dims=[", s_input_tensor->type);
    for (int i = 0; i < s_input_tensor->dims->size; i++) {
        printf("%d%s", s_input_tensor->dims->data[i],
               i < s_input_tensor->dims->size - 1 ? ", " : "");
    }
    printf("]\n");

    ESP_LOGI(TAG, "  Output: type=%d, dims=[", s_output_tensor->type);
    for (int i = 0; i < s_output_tensor->dims->size; i++) {
        printf("%d%s", s_output_tensor->dims->data[i],
               i < s_output_tensor->dims->size - 1 ? ", " : "");
    }
    printf("]\n");

    ESP_LOGI(TAG, "  Arena used: %zu bytes", s_interpreter->arena_used_bytes());
    ESP_LOGI(TAG, "KWS engine initialised ✓");

    return 0;
}

int kws_engine_invoke(const float *features, float *output)
{
    if (!s_interpreter || !s_input_tensor || !s_output_tensor) {
        ESP_LOGE(TAG, "Engine not initialised!");
        return -1;
    }

    int64_t t0 = esp_timer_get_time();

    /*
     * Copy features into input tensor.
     *
     * If the model input is INT8 (quantised), we need to quantise the
     * float features using the input tensor's scale and zero-point.
     */
    if (s_input_tensor->type == kTfLiteFloat32) {
        memcpy(s_input_tensor->data.f, features,
               SPECTRA_N_FRAMES * SPECTRA_N_FEATURES * sizeof(float));
    } else if (s_input_tensor->type == kTfLiteInt8) {
        /* Quantise float → int8 using tensor quantisation params */
        float scale = s_input_tensor->params.scale;
        int32_t zero_point = s_input_tensor->params.zero_point;
        int8_t *input_data = s_input_tensor->data.int8;
        for (int i = 0; i < SPECTRA_N_FRAMES * SPECTRA_N_FEATURES; i++) {
            int32_t val = (int32_t)(features[i] / scale) + zero_point;
            if (val < -128) val = -128;
            if (val > 127) val = 127;
            input_data[i] = (int8_t)val;
        }
    } else {
        ESP_LOGE(TAG, "Unsupported input type: %d", s_input_tensor->type);
        return -1;
    }

    /* Run inference */
    TfLiteStatus status = s_interpreter->Invoke();
    if (status != kTfLiteOk) {
        ESP_LOGE(TAG, "Invoke failed!");
        return -1;
    }

    int64_t t1 = esp_timer_get_time();
    s_last_inference_us = t1 - t0;

    /* Read output and dequantise if needed */
    if (s_output_tensor->type == kTfLiteFloat32) {
        memcpy(output, s_output_tensor->data.f, SPECTRA_N_CLASSES * sizeof(float));
    } else if (s_output_tensor->type == kTfLiteInt8) {
        float scale = s_output_tensor->params.scale;
        int32_t zero_point = s_output_tensor->params.zero_point;
        int8_t *out_data = s_output_tensor->data.int8;
        for (int i = 0; i < SPECTRA_N_CLASSES; i++) {
            output[i] = (out_data[i] - zero_point) * scale;
        }
    }

    /* Apply softmax to get probabilities */
    float max_val = output[0];
    for (int i = 1; i < SPECTRA_N_CLASSES; i++) {
        if (output[i] > max_val) max_val = output[i];
    }
    float sum = 0.0f;
    for (int i = 0; i < SPECTRA_N_CLASSES; i++) {
        output[i] = expf(output[i] - max_val);
        sum += output[i];
    }
    for (int i = 0; i < SPECTRA_N_CLASSES; i++) {
        output[i] /= sum;
    }

    return 0;
}

int kws_engine_predict(const float *features)
{
    float output[SPECTRA_N_CLASSES];
    if (kws_engine_invoke(features, output) != 0) {
        return -1;
    }

    int best = 0;
    for (int i = 1; i < SPECTRA_N_CLASSES; i++) {
        if (output[i] > output[best]) best = i;
    }
    return best;
}

int64_t kws_engine_last_inference_us(void)
{
    return s_last_inference_us;
}

size_t kws_engine_arena_usage(void)
{
    if (s_interpreter) {
        return s_interpreter->arena_used_bytes();
    }
    return 0;
}
